# Generated by Django 4.1.7 on 2023-03-01 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0001_initial"),
        ("cousin", "0002_remove_cousin_parent_cousin_father_cousin_mother"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cousin",
            name="father",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="father",
                to="parent.parent",
            ),
        ),
        migrations.AlterField(
            model_name="cousin",
            name="mother",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mother",
                to="parent.parent",
            ),
        ),
    ]
