# Generated by Django 4.1.7 on 2023-03-01 18:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0003_alter_cousin_father_alter_cousin_mother"),
    ]

    operations = [
        migrations.AddField(
            model_name="cousin",
            name="age",
            field=models.SmallIntegerField(null=True),
        ),
    ]
