# Generated by Django 4.1.7 on 2023-03-02 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0004_grandparent_age_grandparent_first_name_and_more"),
        ("cousin", "0004_cousin_age"),
    ]

    operations = [
        migrations.AddField(
            model_name="cousin",
            name="grandfather",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grandfather",
                to="grandparent.grandparent",
            ),
        ),
        migrations.AddField(
            model_name="cousin",
            name="grandmother",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grandmother",
                to="grandparent.grandparent",
            ),
        ),
    ]
