# Generated by Django 4.1.7 on 2023-03-05 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0005_alter_parent_father_name"),
        ("cousin", "0005_cousin_grandfather_cousin_grandmother"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cousin",
            name="father",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="father",
                to="parent.parent",
            ),
        ),
    ]
