# Generated by Django 4.1.7 on 2023-03-22 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0009_remove_parent_daughter_name_parent_daughter_name"),
        ("grandparent", "0004_grandparent_age_grandparent_first_name_and_more"),
        ("cousin", "0006_alter_cousin_father"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cousin",
            name="grandfather",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grandfather",
                to="grandparent.grandparent",
            ),
        ),
        migrations.AlterField(
            model_name="cousin",
            name="grandmother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="grandmother",
                to="grandparent.grandparent",
            ),
        ),
        migrations.AlterField(
            model_name="cousin",
            name="mother",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mother",
                to="parent.parent",
            ),
        ),
    ]
