# Generated by Django 4.1.7 on 2023-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0007_alter_cousin_grandfather_alter_cousin_grandmother_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="cousin",
            options={"verbose_name_plural": "Cousin Info/Sister_Info"},
        ),
    ]
