# Generated by Django 4.1.7 on 2023-04-19 17:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0012_alter_grandparent_options"),
        ("cousin", "0009_alter_cousin_grandfather_alter_cousin_grandmother"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="cousin",
            name="grandfather",
        ),
        migrations.RemoveField(
            model_name="cousin",
            name="grandmother",
        ),
        migrations.AddField(
            model_name="cousin",
            name="grandfathers",
            field=models.ManyToManyField(
                blank=True, related_name="Grandfathers", to="grandparent.grandparent"
            ),
        ),
        migrations.AddField(
            model_name="cousin",
            name="grandmothers",
            field=models.ManyToManyField(
                blank=True, related_name="Grandmothers", to="grandparent.grandparent"
            ),
        ),
    ]
