# Generated by Django 4.1.7 on 2023-03-01 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0003_remove_grandparent_age_remove_grandparent_first_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandparent",
            name="age",
            field=models.SmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name="grandparent",
            name="first_name",
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AddField(
            model_name="grandparent",
            name="last_name",
            field=models.CharField(max_length=30, null=True),
        ),
    ]
