# Generated by Django 4.1.7 on 2023-03-22 20:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0007_alter_cousin_grandfather_alter_cousin_grandmother_and_more"),
        ("grandparent", "0004_grandparent_age_grandparent_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandparent",
            name="daughter_name",
            field=models.ManyToManyField(
                blank=True, related_name="daugther_name", to="cousin.cousin"
            ),
        ),
    ]
