# Generated by Django 4.1.7 on 2023-03-22 20:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0010_alter_parent_daughter_name_alter_parent_father_name_and_more"),
        ("grandparent", "0005_grandparent_daughter_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grandparent",
            name="daughter_name",
            field=models.ManyToManyField(
                blank=True, related_name="daugther", to="parent.parent"
            ),
        ),
    ]
