# Generated by Django 4.1.7 on 2023-03-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0007_alter_cousin_grandfather_alter_cousin_grandmother_and_more"),
        ("grandparent", "0008_grandparent_grandchildren"),
    ]

    operations = [
        migrations.AlterField(
            model_name="grandparent",
            name="grandchildren",
            field=models.ManyToManyField(
                blank=True, related_name="grandchild", to="cousin.cousin"
            ),
        ),
    ]
