# Generated by Django 4.1.7 on 2023-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0010_alter_parent_daughter_name_alter_parent_father_name_and_more"),
        ("grandparent", "0009_alter_grandparent_grandchildren"),
    ]

    operations = [
        migrations.AddField(
            model_name="grandparent",
            name="son_name",
            field=models.ManyToManyField(
                blank=True, related_name="son", to="parent.parent"
            ),
        ),
    ]
