# Generated by Django 4.1.7 on 2023-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0011_alter_grandparent_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="grandparent",
            options={"verbose_name_plural": "Taylor/Lindsay Grandparents"},
        ),
    ]
