# Generated by Django 4.1.7 on 2023-03-02 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0004_grandparent_age_grandparent_first_name_and_more"),
        ("parent", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="parents",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="grandparent.grandparent",
            ),
        ),
    ]
