# Generated by Django 4.1.7 on 2023-03-02 13:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("grandparent", "0004_grandparent_age_grandparent_first_name_and_more"),
        ("parent", "0002_parent_parents"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="parents",
        ),
        migrations.AddField(
            model_name="parent",
            name="father_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="father_name",
                to="grandparent.grandparent",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="mother_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mother_name",
                to="grandparent.grandparent",
            ),
        ),
    ]
