# Generated by Django 4.1.7 on 2023-03-05 18:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0005_cousin_grandfather_cousin_grandmother"),
        ("parent", "0003_remove_parent_parents_parent_father_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="parent",
            name="daughter_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="daughter_name",
                to="cousin.cousin",
            ),
        ),
        migrations.AddField(
            model_name="parent",
            name="son_name",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="son_name",
                to="cousin.cousin",
            ),
        ),
    ]
