# Generated by Django 4.1.7 on 2023-03-13 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0006_alter_cousin_father"),
        ("parent", "0006_alter_parent_father_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parent",
            name="son_name",
        ),
        migrations.AddField(
            model_name="parent",
            name="son_name",
            field=models.ManyToManyField(to="cousin.cousin"),
        ),
    ]
