# Generated by Django 4.1.7 on 2023-04-05 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cousin", "0007_alter_cousin_grandfather_alter_cousin_grandmother_and_more"),
        ("parent", "0010_alter_parent_daughter_name_alter_parent_father_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="parent",
            name="daughter_name",
            field=models.ManyToManyField(
                blank=True, related_name="daughter", to="cousin.cousin"
            ),
        ),
    ]
