# Generated by Django 4.1.7 on 2023-04-19 17:12

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("parent", "0011_alter_parent_daughter_name"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="parent",
            options={"verbose_name_plural": "Lindsay/Taylor Parents"},
        ),
    ]
